# Generated by Django 5.1.4 on 2025-01-11 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_hobbies_user_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='displayed_name',
            field=models.CharField(max_length=60, verbose_name='Отображаемое имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(max_length=60, unique=True, verbose_name='Имя пользователя'),
        ),
    ]
