# Generated by Django 5.1.4 on 2025-01-11 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_displayed_name_alter_user_nickname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='displayed_name',
            new_name='name',
        ),
    ]
