# Generated by Django 5.1.4 on 2025-01-12 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_displayed_name_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=16, verbose_name='Отображаемое имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.SlugField(max_length=12, unique=True, verbose_name='Имя пользователя'),
        ),
    ]
