# Generated by Django 5.1.4 on 2025-01-18 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_nickname_user_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='slug',
            new_name='nickname',
        ),
    ]
