# Generated by Django 5.1.4 on 2025-01-18 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_rename_slug_user_nickname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='nickname',
            new_name='slug',
        ),
    ]
