# Generated by Django 5.1.4 on 2025-01-18 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Interests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interest',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='interests/', verbose_name='Логотип'),
        ),
        migrations.AlterField(
            model_name='interest',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
